#!/usr/bin/env python3
"""Collect all project files into a single code.md with path details."""

import os

SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "venv", ".opencode", "dist", "build"}
EXT_LANG = {
    ".ts": "typescript", ".tsx": "tsx", ".js": "javascript", ".jsx": "jsx",
    ".css": "css", ".json": "json", ".html": "html", ".md": "markdown",
    ".py": "python", ".sh": "bash", ".yaml": "yaml", ".yml": "yaml",
    ".toml": "toml", ".env": "bash", ".gitignore": "gitignore",
}


def get_lang(filepath):
    _, ext = os.path.splitext(filepath)
    return EXT_LANG.get(ext, "")


def collect(root):
    sections = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        dirnames.sort()
        for fname in sorted(filenames):
            full = os.path.join(dirpath, fname)
            rel = os.path.relpath(full, root)
            if fname == "code.md" or fname == "code.py":
                continue
            try:
                with open(full, "r", encoding="utf-8") as f:
                    content = f.read()
            except (UnicodeDecodeError, PermissionError):
                continue
            lang = get_lang(fname)
            sections.append(f"## `{rel}`\n\n```{lang}\n{content}\n```\n")
    return sections


def main():
    root = os.path.dirname(os.path.abspath(__file__))
    sections = collect(root)
    output = f"# Project Code\n\n> Auto-generated by `code.py` — {len(sections)} files collected\n\n" + "\n---\n\n".join(sections)
    out_path = os.path.join(root, "code.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(output)
    print(f"✓ Generated code.md ({len(sections)} files)")


if __name__ == "__main__":
    main()
